[mypy]
python_version = 3.11
platform = linux
strict = True
files = tests, .devcontainer/gateway, .devcontainer/dns, .devcontainer/agent
mypy_path = .devcontainer/gateway:.devcontainer/dns:.devcontainer/agent
